# Extends the docker-compose.yml for production use.

version: '3.3'
services:
    backend:
    frontend:
        ports:
            - "443:443"
        volumes:
            - /srv/dnascanner/cert:/etc/ssl/dna
            - /srv/dnascanner/nginx:/etc/nginx/conf.d
